config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
	resources :posts do
		resources :comments
	end
	resources :comments do
		resources :comments
	end

  devise_scope :user do
    authenticated :user do
   
       get '/users/sign_out' => 'devise/sessions#destroy'
       root 'posts#index', as: :authenticated_root
       # root 'devise/registrations#edit', as: :authenticated_root
    end
    unauthenticated do
      root 'posts#index', as: :unauthenticated_root
      # root 'users/sessions#new', as: :unauthenticated_root
    end
  end	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, as: :commentable
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
	before_action :find_commentable

	def new
	  @comment = Comment.new
	end

	def create
	  @comment = @commentable.comments.new(comment_params.merge(user_id: current_user.id))

	  if @comment.save
	   redirect_to request.referrer, notice: 'Your comment was successfully posted!'
	  else
	    redirect_to request.referrer, notice: "Your comment wasn't posted!"
	  end
	end

	private

	def comment_params
	  params.require(:comment).permit(:body)
	end

	def find_commentable
	  @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
	  @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts=Post.all
  end

  def show
  end

  def new
    @post=Post.new
  end

  def create
    @post= Post.new(post_params.merge(user_id: current_user.id))
    redirect_to @post if @post.save
  end

  def edit
  end

  def update
    redirect_to @post if @post.save(post_params)
  end

  def destroy
    redirect_to :back if @post.destroy
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/comments/_comment.html.erb
<li><h5 class="mb-3">
  <%= comment.body %> </h5>-
  <h7 class="mb-3">Submitted
    <%= time_ago_in_words(comment.created_at) %> ago - By <%= comment.user.email %></h7>
  <%= form_for [comment, Comment.new] do |f| %>
  <div class="card-body">
    <textarea name="comment[body]" class="form-control mb-1" rows="3" cols="1" placeholder="Enter your message..."></textarea>
    <div class="d-flex align-items-center">
      <button type="submit" class="btn bg-teal-400 btn-labeled btn-labeled-right ml-auto"><b><i class="icon-paperplane"></i></b> Reply</button>
    </div>
  </div>
  <% end %>
  <ul>
    <%= render comment.comments %>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Online Forum</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="page-content">
    <div class="content-wrapper">
      <%= render "layouts/shared/page_header" %>
      <div class="content">
        <%= render "layouts/shared/normal_flash_messages" %>
        <%= yield %>
      </div>
      <%= render "layouts/shared/footer" %>
    </div>
  </div>
</body>

</html>

app/views/layouts/shared/_footer.html.erb
<div class="navbar navbar-expand-lg navbar-light">
  <div class="text-center d-lg-none w-100">
    <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
      <i class="icon-unfold mr-2"></i>
      Footer
    </button>
  </div>
  <div class="navbar-collapse collapse" id="navbar-footer">
    <span class="navbar-text">
      &copy;
      <%= Date.today.cwyear %>. <a href="javascript:void(0);">Online Forum</a> by <a href="javascript:void(0);">Avinash Kumar.</a>
    </span>
  </div>
  <h5><marquee behavior="scroll" direction="right" scrollamount="10">Online Forum - You can share your post here</marquee></h5>
</div>

app/views/layouts/shared/_normal_flash_messages.html.erb
<% if notice.present? %>
	<div class="alert alert-success alert-bordered alert-dismissible">
		<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
		<ul class="list list-square mb-0" style="-webkit-padding-start: 10px!important; -moz-padding-start: 10px!important; -ms-padding-start: 10px!important; -o-padding-start: 10px!important;">
			<li><%= notice %></li>
		</ul>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-danger alert-bordered alert-dismissible">
		<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
		<ul class="list list-square mb-0" style="-webkit-padding-start: 10px!important; -moz-padding-start: 10px!important; -ms-padding-start: 10px!important; -o-padding-start: 10px!important;">
			<li><%= alert %></li>
		</ul>
  </div>
<% end %>

app/views/layouts/shared/_object_flash_messages.html.erb
<% if object.present? %>
	<% if object.errors.any? %>
		<% if object.errors.full_messages.present? %>
		  <div class="alert alert-danger alert-bordered alert-dismissible">
				<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
				<ul class="list list-square mb-0" style="-webkit-padding-start: 10px!important; -moz-padding-start: 10px!important; -ms-padding-start: 10px!important; -o-padding-start: 10px!important;">
					<% object.errors.full_messages.each do |error_message| %>
						<li><%= error_message %></li>
					<% end %>
				</ul>
		  </div>
	  <% end %>
	<% end %>
<% end %>

app/views/layouts/shared/_page_header.html.erb
<div class="page-header page-header-light">
  <div class="page-header-content header-elements-md-inline">
    <div class="page-title d-flex">
      <h4><i class="icon-home mr-2"></i><span class="font-weight-semibold">Online</span> - Forum</h4>
      <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
    </div>
    <h4><a href="/" class="breadcrumb-elements-item"><i class="icon-bubbles3 mr-2"></i>Posts</a></h4>
    <% if user_signed_in? %>
    <div class="header-elements d-none">
      <div class="d-flex justify-content-center">
        <a href="/posts/new" class="btn btn-link btn-float text-default"><i class="icon-pencil text-primary"></i> <span>New Post</span></a>
        <a href="#" class="btn btn-link btn-float text-default"><i class="icon-mailbox text-primary"></i> <span>
            <%= current_user.email%></span></a>
        <a href="<%= destroy_user_session_path %>" class="btn btn-link btn-float text-default"><i class="icon-switch2 text-primary"></i> <span>Logout</span></a>
      </div>
    </div>
    <% else %>
    <div class="header-elements d-none">
      <div class="d-flex justify-content-center">
         <a href="/posts/new" class="btn btn-link btn-float text-default"><i class="icon-pencil text-primary"></i> <span>New Post</span></a>
        <a href="/users/sign_up" class="btn btn-link btn-float text-default"><i class="icon-user-plus text-primary"></i> <span>Sign Up</span></a>
        <a href="/users/sign_in" class="btn btn-link btn-float text-default"><i class="icon-users2 text-primary"></i> <span>Sign In</span></a>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="card">
  <div class="card-header header-elements-inline">
    <div class="media align-items-center align-items-lg-start text-center text-lg-left flex-column flex-lg-row">
      <div class="media-body">
        <h4 class="media-title font-weight-semibold">
          <a href="#">
            <%= link_to(post.title, post) %></a>
        </h5>
        <h4 class="mb-3">
          <%= post.body  %>
        </h5>
        <h7>Submitted
          <%= time_ago_in_words(post.created_at) %> ago - By  <%= post.user.email%></h7>
      </div>
    </div>
    <div class="header-elements">
      <div class="list-icons">
        <a class="list-icons-item" data-action="collapse"></a>
        <a class="list-icons-item" data-action="reload"></a>
        <a class="list-icons-item" data-action="remove"></a>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/new.html.erb
<div class="card">
  <div class="card-header header-elements-inline">
    <h5 class="card-title">Post</h5>
    <div class="header-elements">
      <div class="list-icons">
        <a class="list-icons-item" data-action="collapse"></a>
        <a class="list-icons-item" data-action="reload"></a>
        <a class="list-icons-item" data-action="remove"></a>
      </div>
    </div>
  </div>
  <div class="card-body">
    <%= form_for @post do |f|%>
      <div class="form-group">
        <label>TITLE OF THE POST:</label>
        <input type="text" class="form-control" name="post[title]" placeholder="Title" required="true">
      </div>
      <div class="form-group">
        <label>BODY OF THE POST:</label>
        <textarea name="post[body]" rows="5" cols="5" class="form-control" placeholder="Body Of the post" required="true"></textarea>
      </div>
      <div class="text-right">
        <button type="submit" class="btn btn-primary">Submit form <i class="icon-paperplane ml-2"></i></button>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="card">
  <div class="card-header header-elements-inline">
    <div class="media align-items-center align-items-lg-start text-center text-lg-left flex-column flex-lg-row">
      <div class="media-body">
        <h4 class="media-title font-weight-semibold">
          <a href="#">
            <%= @post.title %></a>
        </h4>
        <h5 class="mb-3">
          <%= @post.body %>
        </h5>
        <h7>Submitted
          <%= time_ago_in_words(@post.created_at) %> ago - By  <%= @post.user.email%></h7>
      </div>
    </div>
    <div class="header-elements">
      <div class="list-icons">
        <a class="list-icons-item" data-action="collapse"></a>
        <a class="list-icons-item" data-action="reload"></a>
        <a class="list-icons-item" data-action="remove"></a>
      </div>
    </div>
  </div>
  <%= form_for [@post, Comment.new] do |f| %>
  <div class="card-body">
    <textarea name="comment[body]" class="form-control mb-1" rows="3" cols="1" placeholder="Enter your message..."></textarea>
    <div class="d-flex align-items-center">
      <button type="submit" class="btn bg-teal-400 btn-labeled btn-labeled-right ml-auto"><b><i class="icon-paperplane"></i></b> Add Comment</button>
    </div>
  </div>
  <% end %>
  <ul>
    <%= render @post.comments %>
  </ul>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>